name: Clang analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_clang_static_analyser:
    name: Clang static analyzer
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tools meson ninja-build python3-bs4 \
            $(cat packages/ubuntu-24.04-apt.txt)

      - name: Restore subprojects cache
        uses: actions/cache@v4
        with:
          path: subprojects.tar
          key: subprojects-${{ hashFiles('subprojects/*.wrap') }}-1

      - name: Extract or Fetch subprojects
        run: |
          if [ -f subprojects.tar ]; then
            tar -xf subprojects.tar
          else
            chmod +x scripts/fetch-and-tar-subprojects.sh
            ./scripts/fetch-and-tar-subprojects.sh
            tar -xf subprojects.tar
          fi

      - name: Meson setup
        run: |
          meson setup build \
            -Dbuildtype=debug \
            -Dunit_tests=disabled \
            -Duse_alsa=false \
            -Duse_opengl=false \
            -Duse_zlib_ng=false

      - name: Build and run scan-build
        run: |
          ninja -C build scan-build
          mv build/meson-logs/scanbuild report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: clang-analysis-report
          path: report

      - name: Summarize report
        run: |
          # Verhindert Fehler, falls kein HTML-Report gefunden wurde
          if [ -d report ]; then
            ./scripts/count-clang-bugs.py report/*/index.html
          else
            echo "No bugs found or report missing."
          fi

